### ISSUE TITLE
Bug in position of negative strand guides

### ISSUE THREAD

**Issue by felicityallen** [sanjanalab/GUIDES#4] opened 2019-04-29 13:26 UTC
I think you may have a bug in the positions of the negative strand guides you return.

e.g. If I use your tool to return 6 guides against the Mouse gene ADNP (GRCm38), I get the guides below, 

ID                           Sequence                                  Gene     Chrom   True Cut Site Position  Your PAM position
GUIDES_sg025    TGTTGCTAGTATACACACCA    ADNP    2       168183370       168183373       +      
GUIDES_sg026    TGGTTGAGTAGGGTATCTGT    ADNP    2       168183876       168183879       +       
GUIDES_sg027    TCCACTTCTGAGTGGCACAG    ADNP    2       168184054       168184057       +       
GUIDES_sg028    TTGGCAGTTTAAGAAAAGCC    ADNP    2       168189347       168189326       -       
GUIDES_sg029    AACACTACATGGGAGGATGT    ADNP    2       168187603       168187625       -       
GUIDES_sg030    CATGGGAGGATGTAGGACTG    ADNP    2       168187596        168187632       -       

Seems like your positive strand guides are fine (3 after the cut site, as I’d expect), but the negative ones are ~20-60nt out, with an inconsistent pattern I can’t make sense of.  
Am I mistaken?

**Comment by joshim5** [comment] 2019-07-09 19:35
Thanks for reporting this. This is fixed in https://github.com/sanjanalab/GUIDES/pull/5.

I am recomputing the data for the public version (guides.sanjanalab.org), which should be ready in a few hours.

**Closed** 2019-07-09 19:35 UTC

**Comment by joshim5** [comment] 2019-07-10 12:55
I confirmed the issue is resolved by designing a library for ADNP, as above. Here is the output from GUIDES from some of your sequences above.

sequence,cut position in chromosome,strand
AACACTACATGGGAGGATGT,168187603,+
CATGGGAGGATGTAGGACTG,168187596,-
TGTTGCTAGTATACACACCA,168183370,-

These match your expected results, pasted above, as well as my own tests on BLAT.
